export const recommended_spaces = [
  {
    id: 1,
    name: "서초구 작은음악회 집",
    description: "월드컵 경기장의 작고 귀여운 아기자기한 키즈카페",
  },
  {
    id: 2,
    name: "서초구 작은음악회 집",
    description: "월드컵 경기장의 작고 귀여운 아기자기한 키즈카페",
  },
  {
    id: 3,
    name: "서초구 작은음악회 집",
    description: "월드컵 경기장의 작고 귀여운 아기자기한 키즈카페",
  },
  {
    id: 4,
    name: "서초구 작은음악회 집",
    description: "월드컵 경기장의 작고 귀여운 아기자기한 키즈카페",
  },
  {
    id: 5,
    name: "서초구 작은음악회 집",
    description: "월드컵 경기장의 작고 귀여운 아기자기한 키즈카페",
  },
];

export const search_results = {
  data: [
    {
      id: 1,
      name: "성북구 벌집어린이",
      description: "동화 속 오두막같은 키즈카페",
      reviewCount: 112,
      rating: 4.7,
      imageUrl: "https://example.com/image1.jpg",
      type: "실내 놀이",
      location: "성북구 안암동",
      holiday: ["월"],
    },
    {
      id: 2,
      name: "성북구 벌집어린이",
      description: "동화 속 오두막같은 키즈카페",
      reviewCount: 112,
      rating: 4.7,
      imageUrl: "https://example.com/image1.jpg",
      type: "실내 놀이",
      location: "성북구 안암동",
      holiday: ["토", "일"],
    },
    {
      id: 3,
      name: "성북구 벌집어린이",
      description: "동화 속 오두막같은 키즈카페",
      reviewCount: 112,
      rating: 4.7,
      imageUrl: "https://example.com/image1.jpg",
      type: "실내 놀이",
      location: "성북구 안암동",
      holiday: ["월"],
    },
    {
      id: 4,
      name: "성북구 벌집어린이",
      description: "동화 속 오두막같은 키즈카페",
      reviewCount: 112,
      rating: 4.7,
      imageUrl: "https://example.com/image1.jpg",
      type: "실내 놀이",
      location: "성북구 안암동",
      holiday: ["토", "일"],
    },
    {
      id: 5,
      name: "성북구 벌집어린이",
      description: "동화 속 오두막같은 키즈카페",
      reviewCount: 112,
      rating: 4.7,
      imageUrl: "https://example.com/image1.jpg",
      type: "실내 놀이",
      location: "성북구 안암동",
      holiday: ["월"],
    },
    {
      id: 6,
      name: "성북구 벌집어린이",
      description: "동화 속 오두막같은 키즈카페",
      reviewCount: 112,
      rating: 4.7,
      imageUrl: "https://example.com/image1.jpg",
      type: "실내 놀이",
      location: "성북구 안암동",
      holiday: ["토", "일"],
    },
    {
      id: 7,
      name: "성북구 벌집어린이",
      description: "동화 속 오두막같은 키즈카페",
      reviewCount: 112,
      rating: 4.7,
      imageUrl: "https://example.com/image1.jpg",
      type: "실내 놀이",
      location: "성북구 안암동",
      holiday: ["월"],
    },
  ],
  totalResults: 50,
  currentPage: 1,
  totalPages: 5,
};
